version: '3'

services:
  db:
    image: postgres:15.2-alpine
    container_name: db
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro


volumes:
  db:
